"""Palmer News headless API — the primary interface for this platform.
Agents are the main target audience, not human browsers; the HTML site
(build_site.py / run_pipeline.py output) is a secondary, human-facing view
of the same underlying data. This is what should actually be integrated
against: structured JSON, an OpenAPI schema at /openapi.json (auto-
generated by FastAPI) so any agent framework can introspect what's
callable without a human reading docs first, and interactive docs at /docs
for humans who do want to look.

Read-only — this API doesn't trigger pipeline runs or write anything. Run
run_pipeline.py (directly or via scheduler_loop.py) to produce new data;
this just serves what's already in the store.

Run locally: python api_server.py  (serves on http://localhost:8420)
Or: uvicorn api_server:app --reload
"""
from __future__ import annotations

import sys
from datetime import datetime, timezone
from typing import Optional

# See run_pipeline.py for why — Windows console encoding can't represent
# most non-ASCII characters (confirmed crash on a Czech name), and this
# is now routine with global sports/entertainment sources in the mix.
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")

from dotenv import load_dotenv

load_dotenv()

from fastapi import BackgroundTasks, Depends, FastAPI, Header, HTTPException, Query, Request
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

from build_site import ARTICLE_CATEGORIES, BASE_URL, _iso_when, clean_title
from fetch_polymarket import fetch_polymarket_markets
from store import (
    check_rate_limit,
    get_article_by_slug,
    get_cached_markets,
    get_conn,
    save_markets,
    validate_api_key,
)

MARKETS_CACHE_TTL_S = 30  # live odds, but no API consumer needs sub-30s freshness
RATE_LIMIT_PER_MINUTE = 30
# Load-tested this server at up to 300 concurrent requests (2026-08-26) —
# 100% success rate even under that load (slows down under heavy
# concurrency, single-process dev setup, but never errors/drops
# connections), sustained aggregate throughput ~40-75 req/s. 30/min per
# key (0.5/sec sustained) leaves large headroom below that ceiling even
# with dozens of keys active at once.


app = FastAPI(
    title="Palmer News API",
    description=(
        "Headless JSON API for Palmer News — an automated news platform pairing "
        "AI-synthesized news coverage (BBC/Guardian/Al Jazeera, rewritten under a "
        "grounding rule with an independent verify pass) with live Polymarket "
        "prediction-market odds. Built primarily for agent/programmatic consumption, "
        "not human browsing — see /docs for the interactive schema, or /openapi.json "
        "for the raw spec any agent framework can introspect directly."
    ),
    version="0.1.0",
)

# Open CORS — this API is meant to be broadly callable by any agent/script,
# not locked to one frontend origin.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["GET"],
    allow_headers=["*"],
)


def require_api_key(request: Request, x_api_key: Optional[str] = Header(None)):
    """Applied to every /api/* route. Root (/), /docs, and /openapi.json
    stay open — developers should be able to read the schema before they
    need a key, same convention most API products use. Get a key with
    manage_keys.py."""
    if not x_api_key:
        raise HTTPException(401, "Missing API key — pass it in the X-API-Key header. "
                             "Get one with: python manage_keys.py create \"your app name\"")
    conn = get_conn()
    if not validate_api_key(conn, x_api_key):
        raise HTTPException(401, "Invalid or revoked API key.")

    allowed, remaining, reset_in = check_rate_limit(conn, x_api_key, RATE_LIMIT_PER_MINUTE)
    request.state.rate_limit_remaining = remaining
    request.state.rate_limit_reset = reset_in
    if not allowed:
        raise HTTPException(
            429,
            f"Rate limit exceeded ({RATE_LIMIT_PER_MINUTE}/min). Try again in {reset_in:.0f}s.",
            headers={"Retry-After": str(int(reset_in) + 1)},
        )


@app.middleware("http")
async def add_rate_limit_headers(request: Request, call_next):
    response = await call_next(request)
    remaining = getattr(request.state, "rate_limit_remaining", None)
    if remaining is not None:
        response.headers["X-RateLimit-Limit"] = str(RATE_LIMIT_PER_MINUTE)
        response.headers["X-RateLimit-Remaining"] = str(remaining)
        response.headers["X-RateLimit-Reset"] = f"{request.state.rate_limit_reset:.0f}"
    return response


class MarketOut(BaseModel):
    title: str
    url: Optional[str] = None
    outcomes: Optional[list[str]] = None
    outcome_prices: Optional[list[str]] = None
    end_date: Optional[str] = None
    match_reason: Optional[str] = None


class ArticleSummary(BaseModel):
    slug: Optional[str]
    category: str
    headline: str
    summary: Optional[str]
    image_url: Optional[str]
    published_at: Optional[str]
    source_count: int
    corroborated: bool
    verify_status: str
    matched_market: Optional[MarketOut]
    permalink: Optional[str]
    api_url: Optional[str]


class ArticleDetail(ArticleSummary):
    body: Optional[str]
    sources: list[str]


class ArticlesPage(BaseModel):
    count: int
    limit: int
    offset: int
    articles: list[ArticleSummary]


def _row_to_summary(row: dict) -> ArticleSummary:
    matched = row.get("matched_market")
    market_out = None
    if matched:
        market_out = MarketOut(
            title=matched.get("title", ""),
            url=matched.get("url"),
            outcomes=matched.get("outcomes"),
            outcome_prices=matched.get("outcome_prices"),
            end_date=matched.get("end_date"),
            match_reason=matched.get("match_reason"),
        )
    slug = row.get("slug")
    return ArticleSummary(
        slug=slug,
        category=row.get("category", ""),
        headline=row.get("rewritten_title") or clean_title(row.get("title", "")),
        summary=row.get("rewritten_summary") or row.get("description"),
        image_url=row.get("image_url"),
        published_at=_iso_when(row) or None,
        source_count=row.get("source_count", 1),
        corroborated=bool(row.get("corroborated")),
        verify_status=row.get("verify_status", "not_attempted"),
        matched_market=market_out,
        permalink=f"{BASE_URL}/articles/{slug}.html" if slug else None,
        api_url=f"{BASE_URL}/api/articles/{slug}" if slug else None,
    )


@app.get("/", tags=["meta"])
def root():
    """API entrypoint — points to the schema and key endpoints."""
    return {
        "name": "Palmer News API",
        "docs": "/docs",
        "openapi_schema": "/openapi.json",
        "endpoints": {
            "articles": "/api/articles",
            "article_detail": "/api/articles/{slug}",
            "markets": "/api/markets",
            "categories": "/api/categories",
        },
        "note": "This is a development-stage project — content is AI-generated "
                "with no human editorial review. See each article's verify_status "
                "and corroborated fields before treating it as reliable.",
        "auth": "All /api/* endpoints require an API key in the X-API-Key header. "
                "Get one with: python manage_keys.py create \"your app name\"",
    }


@app.get("/api/categories", tags=["meta"], dependencies=[Depends(require_api_key)])
def categories():
    return {"categories": ARTICLE_CATEGORIES}


@app.get("/api/articles", response_model=ArticlesPage, tags=["articles"], dependencies=[Depends(require_api_key)])
def list_articles(
    category: Optional[str] = Query(None, description=f"Filter by one of: {', '.join(ARTICLE_CATEGORIES)}"),
    q: Optional[str] = Query(None, description="Keyword search across headline and summary "
                              "(case-insensitive substring match)"),
    limit: int = Query(20, ge=1, le=200),
    offset: int = Query(0, ge=0),
    since: Optional[str] = Query(None, description="ISO 8601 timestamp — only articles first "
                                  "seen after this time. Useful for agents polling incrementally "
                                  "instead of re-fetching everything each time."),
):
    conn = get_conn()
    category_norm = category.upper() if category else None
    if category_norm and category_norm not in ARTICLE_CATEGORIES:
        raise HTTPException(400, f"category must be one of: {', '.join(ARTICLE_CATEGORIES)}")

    where = ["held_back = 0"]
    params: list = []
    if category_norm:
        where.append("category = ?")
        params.append(category_norm)
    if q:
        where.append("(rewritten_title LIKE ? OR title LIKE ? OR rewritten_summary LIKE ?)")
        like = f"%{q}%"
        params.extend([like, like, like])
    if since:
        try:
            since_ts = datetime.fromisoformat(since).timestamp()
        except ValueError:
            raise HTTPException(400, "since must be a valid ISO 8601 timestamp")
        where.append("first_seen > ?")
        params.append(since_ts)

    where_sql = " WHERE " + " AND ".join(where)
    total = conn.execute(f"SELECT COUNT(*) c FROM articles{where_sql}", params).fetchone()["c"]
    rows = conn.execute(
        f"SELECT * FROM articles{where_sql} ORDER BY first_seen DESC LIMIT ? OFFSET ?",
        params + [limit, offset],
    ).fetchall()

    import json as _json
    articles = []
    for row in rows:
        d = dict(row)
        d["matched_market"] = _json.loads(d["matched_market_json"]) if d.get("matched_market_json") else None
        articles.append(_row_to_summary(d))

    return ArticlesPage(count=total, limit=limit, offset=offset, articles=articles)


@app.get("/api/articles/{slug}", response_model=ArticleDetail, tags=["articles"], dependencies=[Depends(require_api_key)])
def article_detail(slug: str):
    conn = get_conn()
    row = get_article_by_slug(conn, slug)
    if not row or row.get("held_back"):
        raise HTTPException(404, "article not found")

    summary = _row_to_summary(row)
    sources = []
    # cluster_sources isn't persisted verbatim; source_count + source give a
    # partial picture — good enough for now, worth a real column later if
    # agents need the exact outlet list.
    if row.get("source"):
        sources.append(row["source"])

    return ArticleDetail(
        **summary.model_dump(),
        body=row.get("detail_body") or row.get("rewritten_summary") or row.get("description"),
        sources=sources,
    )


def _refresh_markets_cache(cache_key: str, limit: int) -> None:
    """Runs after the response is already sent (BackgroundTasks) — refreshes
    the cache for next time without making the current caller wait."""
    conn = get_conn()
    fresh = fetch_polymarket_markets(limit=limit)
    if fresh:
        save_markets(conn, cache_key, fresh)


@app.get("/api/markets", tags=["markets"], dependencies=[Depends(require_api_key)])
def markets(background_tasks: BackgroundTasks, limit: int = Query(40, ge=1, le=200)):
    """Stale-while-revalidate: always serve instantly from cache (even a
    stale one) and refresh in the background, rather than ever blocking a
    request on a live Polymarket fetch. Measured live-fetch latency was
    ~9-13s (direct connection fails on this network, falls back to a
    Lambda relay) — unacceptable to put in the request path for an API
    whose whole pitch is being faster than the slow incumbents. Only the
    very first-ever request (no cache at all yet) pays that cost; every
    request after that is sub-20ms regardless of freshness."""
    conn = get_conn()
    cache_key = f"limit={limit}"

    fresh_cached = get_cached_markets(conn, cache_key, MARKETS_CACHE_TTL_S)
    if fresh_cached is not None:
        return {"count": len(fresh_cached), "markets": fresh_cached, "cached": True, "stale": False}

    stale_cached = get_cached_markets(conn, cache_key, max_age_s=10**9)  # any age
    if stale_cached is not None:
        background_tasks.add_task(_refresh_markets_cache, cache_key, limit)
        return {"count": len(stale_cached), "markets": stale_cached, "cached": True, "stale": True}

    # No cache at all yet (first-ever request) — nothing to serve, must block.
    fresh = fetch_polymarket_markets(limit=limit)
    save_markets(conn, cache_key, fresh)
    return {"count": len(fresh), "markets": fresh, "cached": False, "stale": False}


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host="0.0.0.0", port=8420)
