"""Palmer News headless API — the primary interface for this platform.
Agents are the main target audience, not human browsers; the HTML site
(build_site.py / run_pipeline.py output) is a secondary, human-facing view
of the same underlying data. This is what should actually be integrated
against: structured JSON, an OpenAPI schema at /openapi.json (auto-
generated by FastAPI) so any agent framework can introspect what's
callable without a human reading docs first, and interactive docs at /docs
for humans who do want to look.

Read-only — this API doesn't trigger pipeline runs or write anything. Run
run_pipeline.py (directly or via scheduler_loop.py) to produce new data;
this just serves what's already in the store.

Run locally: python api_server.py  (serves on http://localhost:8420)
Or: uvicorn api_server:app --reload
"""
from __future__ import annotations

from datetime import datetime, timezone
from typing import Optional

from dotenv import load_dotenv

load_dotenv()

from fastapi import FastAPI, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

from build_site import BASE_URL, _iso_when
from fetch_polymarket import fetch_polymarket_markets
from store import get_article_by_slug, get_conn

app = FastAPI(
    title="Palmer News API",
    description=(
        "Headless JSON API for Palmer News — an automated news platform pairing "
        "AI-synthesized news coverage (BBC/Guardian/Al Jazeera, rewritten under a "
        "grounding rule with an independent verify pass) with live Polymarket "
        "prediction-market odds. Built primarily for agent/programmatic consumption, "
        "not human browsing — see /docs for the interactive schema, or /openapi.json "
        "for the raw spec any agent framework can introspect directly."
    ),
    version="0.1.0",
)

# Open CORS — this API is meant to be broadly callable by any agent/script,
# not locked to one frontend origin.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["GET"],
    allow_headers=["*"],
)


class MarketOut(BaseModel):
    title: str
    url: Optional[str] = None
    outcomes: Optional[list[str]] = None
    outcome_prices: Optional[list[str]] = None
    end_date: Optional[str] = None
    match_reason: Optional[str] = None


class ArticleSummary(BaseModel):
    slug: Optional[str]
    category: str
    headline: str
    summary: Optional[str]
    image_url: Optional[str]
    published_at: Optional[str]
    source_count: int
    corroborated: bool
    verify_status: str
    matched_market: Optional[MarketOut]
    permalink: Optional[str]
    api_url: Optional[str]


class ArticleDetail(ArticleSummary):
    body: Optional[str]
    sources: list[str]


class ArticlesPage(BaseModel):
    count: int
    limit: int
    offset: int
    articles: list[ArticleSummary]


def _row_to_summary(row: dict) -> ArticleSummary:
    matched = row.get("matched_market")
    market_out = None
    if matched:
        market_out = MarketOut(
            title=matched.get("title", ""),
            url=matched.get("url"),
            outcomes=matched.get("outcomes"),
            outcome_prices=matched.get("outcome_prices"),
            end_date=matched.get("end_date"),
            match_reason=matched.get("match_reason"),
        )
    slug = row.get("slug")
    return ArticleSummary(
        slug=slug,
        category=row.get("category", ""),
        headline=row.get("rewritten_title") or row.get("title", ""),
        summary=row.get("rewritten_summary"),
        image_url=row.get("image_url"),
        published_at=_iso_when(row) or None,
        source_count=row.get("source_count", 1),
        corroborated=bool(row.get("corroborated")),
        verify_status=row.get("verify_status", "not_attempted"),
        matched_market=market_out,
        permalink=f"{BASE_URL}/articles/{slug}.html" if slug else None,
        api_url=f"{BASE_URL}/api/articles/{slug}" if slug else None,
    )


@app.get("/", tags=["meta"])
def root():
    """API entrypoint — points to the schema and key endpoints."""
    return {
        "name": "Palmer News API",
        "docs": "/docs",
        "openapi_schema": "/openapi.json",
        "endpoints": {
            "articles": "/api/articles",
            "article_detail": "/api/articles/{slug}",
            "markets": "/api/markets",
            "categories": "/api/categories",
        },
        "note": "This is a development-stage project — content is AI-generated "
                "with no human editorial review. See each article's verify_status "
                "and corroborated fields before treating it as reliable.",
    }


@app.get("/api/categories", tags=["meta"])
def categories():
    return {"categories": ["MARKET", "FINANCE", "TECHNOLOGY"]}


@app.get("/api/articles", response_model=ArticlesPage, tags=["articles"])
def list_articles(
    category: Optional[str] = Query(None, description="Filter by MARKET, FINANCE, or TECHNOLOGY"),
    limit: int = Query(20, ge=1, le=200),
    offset: int = Query(0, ge=0),
    since: Optional[str] = Query(None, description="ISO 8601 timestamp — only articles first "
                                  "seen after this time. Useful for agents polling incrementally "
                                  "instead of re-fetching everything each time."),
):
    conn = get_conn()
    category_norm = category.upper() if category else None
    if category_norm and category_norm not in ("MARKET", "FINANCE", "TECHNOLOGY"):
        raise HTTPException(400, "category must be MARKET, FINANCE, or TECHNOLOGY")

    where = ["held_back = 0"]
    params: list = []
    if category_norm:
        where.append("category = ?")
        params.append(category_norm)
    if since:
        try:
            since_ts = datetime.fromisoformat(since).timestamp()
        except ValueError:
            raise HTTPException(400, "since must be a valid ISO 8601 timestamp")
        where.append("first_seen > ?")
        params.append(since_ts)

    where_sql = " WHERE " + " AND ".join(where)
    total = conn.execute(f"SELECT COUNT(*) c FROM articles{where_sql}", params).fetchone()["c"]
    rows = conn.execute(
        f"SELECT * FROM articles{where_sql} ORDER BY first_seen DESC LIMIT ? OFFSET ?",
        params + [limit, offset],
    ).fetchall()

    import json as _json
    articles = []
    for row in rows:
        d = dict(row)
        d["matched_market"] = _json.loads(d["matched_market_json"]) if d.get("matched_market_json") else None
        articles.append(_row_to_summary(d))

    return ArticlesPage(count=total, limit=limit, offset=offset, articles=articles)


@app.get("/api/articles/{slug}", response_model=ArticleDetail, tags=["articles"])
def article_detail(slug: str):
    conn = get_conn()
    row = get_article_by_slug(conn, slug)
    if not row or row.get("held_back"):
        raise HTTPException(404, "article not found")

    summary = _row_to_summary(row)
    sources = []
    # cluster_sources isn't persisted verbatim; source_count + source give a
    # partial picture — good enough for now, worth a real column later if
    # agents need the exact outlet list.
    if row.get("source"):
        sources.append(row["source"])

    return ArticleDetail(
        **summary.model_dump(),
        body=row.get("detail_body") or row.get("rewritten_summary"),
        sources=sources,
    )


@app.get("/api/markets", tags=["markets"])
def markets(limit: int = Query(40, ge=1, le=200)):
    """Live Polymarket data, fetched fresh on each call (not cached) — these
    are supposed to be current odds, not a stale snapshot."""
    return {"count": None, "markets": fetch_polymarket_markets(limit=limit)}


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host="0.0.0.0", port=8420)
